### ISSUE TITLE
Missing dependency python-tk

### ISSUE THREAD

**Issue by matosinho** [mateusmenezes95/ur5_simulation#2]
It would be nice to add that python-tk is also a dependency in the readME dependency section. Here is the command that I've used to install it: `apt-get install python-tk`

**Comment by mateusmenezes95** [comment]
> It would be nice to add that python-tk is also a dependency in the readME dependency section. Here is the command that I've used to install it: `apt-get install python-tk`

I think it is not necessary to put it as a dependency as it is not directly included in some code of the package. I think this dependency is a system dependency and the problem maybe occurred because you are using a docker container
