### ISSUE TITLE
Joint controller with execution issues

### ISSUE THREAD

**Issue by matosinho** [mateusmenezes95/ur5_simulation#3]
The exeception in line 48 of joint_controller.py is not working because ROSExecption is not recognized. I changed from:
`except ROSException as error:` to `except rospy.exceptions.ROSException as error:`

But then another problem happened:
```
[ERROR] [1621224970.628369]: timeout exceeded while waiting for message on topic /joint_states
Traceback (most recent call last):
  File "/ros_workspaces/ws_ur5_project/src/ur5_simulation/scripts/joints_controller_node.py", line 43, in <module>
    if max(abs(joint_set - joint_controller.get_joints_state())) < 0.05:    # avoid unnecessary movement
  File "/ros_workspaces/ws_ur5_project/src/ur5_simulation/src/ur5_simulation/joint_controller.py", line 95, in get_joints_state
    return np.array(self.__get_joints_state_ordered().position)
AttributeError: 'NoneType' object has no attribute 'position'
```

I'm wondering if the updated file was merged in the last PR.

**Comment by mateusmenezes95** [comment]
This is a bug that deserves attention, but did you run the node after the simulation? The problem occurred because there wasn't any `/joint_states` topic available, and this topic is launched together with the simulation.

**Comment by matosinho** [comment]
Sorry, it was late... I actually didn't.... It's working beatifully! Nice error tracking BTW. Thank you! One of the best ReadME I saw so far.
