### ISSUE TITLE
Wrong calculations in inverse kinematics

### ISSUE THREAD

**Issue by rafaelsqueiroz** [mateusmenezes95/ur5_simulation#6]
Method `calculate_inverse_kinematics`, from #5, is not reliable. For a certain dh matrix, it outputs the proper joint angles, whilst for others it doesn't. 

Examples below:

for q = [0, -1.57, 0, 0, 0, 1.32]:

tf:
[[ 0.969  0.247  0.    -0.095]
 [-0.     0.    -1.    -0.191]
 [-0.247  0.969  0.     0.906]
 [ 0.     0.     0.     1.   ]]

DH matrix:
      θi        di   a(i-1)    α(i-1)
i1  0.00  0.089159  0.00000  0.000000
i2 -1.57  0.000000  0.00000  1.570796
i3  0.00  0.000000 -0.42500  0.000000
i4  0.00  0.109100 -0.39225  0.000000
i5  0.00  0.094650  0.00000  1.570796
i6  1.32  0.082300  0.00000 -1.570796

Calculated inverse matrix from DH matrix:
[-0.004 -1.891  0.942  0.     0.004  2.892] 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

for q = [1.2, -0.47, 0.73, 0, 0, 1.32]:

tf:
[[-0.003 -0.362  0.932 -0.087]
 [-0.009 -0.932 -0.362 -0.753]
 [ 1.    -0.009  0.     0.089]
 [ 0.     0.     0.     1.   ]]

DH matrix:
      θi        di   a(i-1)    α(i-1)
i1  1.20  0.089159  0.00000  0.000000
i2 -0.47  0.000000  0.00000  1.570796
i3  0.73  0.000000 -0.42500  0.000000
i4  0.00  0.109100 -0.39225  0.000000
i5  0.00  0.094650  0.00000  1.570796
i6  1.32  0.082300  0.00000 -1.570796

Calculated inverse matrix from DH matrix:
[ 1.201 -0.549  0.88   0.     0.018  1.58 ] 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

for q = [0, -1.57, 0, 0, 0, 1.57]:

tf:
[[ 1.     0.     0.    -0.095]
 [-0.     0.    -1.    -0.191]
 [ 0.     1.     0.     0.906]
 [ 0.     0.     0.     1.   ]]

DH matrix:
      θi        di   a(i-1)    α(i-1)
i1  0.00  0.089159  0.00000  0.000000
i2 -1.57  0.000000  0.00000  1.570796
i3  0.00  0.000000 -0.42500  0.000000
i4  0.00  0.109100 -0.39225  0.000000
i5  0.00  0.094650  0.00000  1.570796
i6  1.57  0.082300  0.00000 -1.570796

Calculated inverse matrix from DH matrix:
[-0.004 -1.891  0.942  0.     0.004  3.142]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

for q = [1.64, -0.45, 0.45, 0, 3.14, 1.57]:

tf:
[[ 0.    -0.071 -0.997  0.08 ]
 [-0.001  0.997 -0.071 -0.771]
 [ 1.     0.001 -0.     0.179]
 [ 0.     0.     0.     1.   ]]

DH matrix:
      θi        di   a(i-1)    α(i-1)
i1  1.64  0.089159  0.00000  0.000000
i2 -0.45  0.000000  0.00000  1.570796
i3  0.45  0.000000 -0.42500  0.000000
i4  0.00  0.109100 -0.39225  0.000000
i5  3.14  0.094650  0.00000  1.570796
i6  1.57  0.082300  0.00000 -1.570796

Calculated inverse matrix from DH matrix:
[ 1.64  -0.452  0.456  0.     3.111  1.57 ]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

for q = [0, -1.57, 0, 0, 0, 1.57]:

tf:
[[ 1.     0.     0.    -0.095]
 [-0.     0.    -1.    -0.191]
 [ 0.     1.     0.     0.906]
 [ 0.     0.     0.     1.   ]]

DH matrix:
      θi        di   a(i-1)    α(i-1)
i1  0.00  0.089159  0.00000  0.000000
i2 -1.57  0.000000  0.00000  1.570796
i3  0.00  0.000000 -0.42500  0.000000
i4  0.00  0.109100 -0.39225  0.000000
i5  0.00  0.094650  0.00000  1.570796
i6  1.57  0.082300  0.00000 -1.570796

Calculated inverse matrix from DH matrix:
[-0.004 -1.891  0.942  0.     0.004  3.142]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

for q = [1.39, -0.87, 1.41, -0.5, 1.32, 0]:

tf:
[[ 0.998 -0.007  0.07   0.004]
 [ 0.07  -0.039 -0.997 -0.698]
 [ 0.01   0.999 -0.039  0.115]
 [ 0.     0.     0.     1.   ]]

DH matrix:
      θi        di   a(i-1)    α(i-1)
i1  1.39  0.089159  0.00000  0.000000
i2 -0.87  0.000000  0.00000  1.570796
i3  1.41  0.000000 -0.42500  0.000000
i4 -0.50  0.109100 -0.39225  0.000000
i5  1.32  0.094650  0.00000  1.570796
i6  0.00  0.082300  0.00000 -1.570796

Calculated inverse matrix from DH matrix:
[ 1.39  -0.872  1.412 -0.5    1.32  -0.   ]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

for q = [0, -1.57, 0, 0, 0, 1.57]:

tf:
[[ 1.     0.     0.    -0.095]
 [-0.     0.    -1.    -0.191]
 [ 0.     1.     0.     0.906]
 [ 0.     0.     0.     1.   ]]

DH matrix:
      θi        di   a(i-1)    α(i-1)
i1  0.00  0.089159  0.00000  0.000000
i2 -1.57  0.000000  0.00000  1.570796
i3  0.00  0.000000 -0.42500  0.000000
i4  0.00  0.109100 -0.39225  0.000000
i5  0.00  0.094650  0.00000  1.570796
i6  1.57  0.082300  0.00000 -1.570796

Calculated inverse matrix from DH matrix:
[-0.004 -1.891  0.942  0.     0.004  3.142]

**Comment by mateusmenezes95** [comment]
Fixed in #5 and https://github.com/mateusmenezes95/ur5_simulation/commit/c8478ce959e30317f88366513a976bf3d9dfe22b
